//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportsSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportsSource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M3Reports.ReportsSource", typeof(ReportsSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступность для клиентов.
        /// </summary>
        internal static string AccessForClients {
            get {
                return ResourceManager.GetString("AccessForClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес установки.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время возникновения.
        /// </summary>
        internal static string AppearTime {
            get {
                return ResourceManager.GetString("AppearTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначен.
        /// </summary>
        internal static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банкомат.
        /// </summary>
        internal static string ATM {
            get {
                return ResourceManager.GetString("ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа УС.
        /// </summary>
        internal static string AtmGroups {
            get {
                return ResourceManager.GetString("AtmGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя банкомата.
        /// </summary>
        internal static string AtmName {
            get {
                return ResourceManager.GetString("AtmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системный номер.
        /// </summary>
        internal static string AtmNumber {
            get {
                return ResourceManager.GetString("AtmNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициатор заявки.
        /// </summary>
        internal static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступность.
        /// </summary>
        internal static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступность сети банкоматов.
        /// </summary>
        internal static string AvailabilityOfAtmNetwork {
            get {
                return ResourceManager.GetString("AvailabilityOfAtmNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение банка.
        /// </summary>
        internal static string BankDivision {
            get {
                return ResourceManager.GetString("BankDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простой по сторонним причинам.
        /// </summary>
        internal static string BreakingOtherReasons {
            get {
                return ResourceManager.GetString("BreakingOtherReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остаток денежной наличности.
        /// </summary>
        internal static string CashBalance {
            get {
                return ResourceManager.GetString("CashBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача наличности.
        /// </summary>
        internal static string CashWithdrawal {
            get {
                return ResourceManager.GetString("CashWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кассета.
        /// </summary>
        internal static string Cassette {
            get {
                return ResourceManager.GetString("Cassette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата последнего изменения.
        /// </summary>
        internal static string ChangeData {
            get {
                return ResourceManager.GetString("ChangeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступность по связи.
        /// </summary>
        internal static string CommunicationAvailability {
            get {
                return ResourceManager.GetString("CommunicationAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критичность.
        /// </summary>
        internal static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее состояние.
        /// </summary>
        internal static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата достижения минимального остатка.
        /// </summary>
        internal static string DateTimeMin {
            get {
                return ResourceManager.GetString("DateTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата полного опустошения кассет.
        /// </summary>
        internal static string DateTimeZero {
            get {
                return ResourceManager.GetString("DateTimeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День недели.
        /// </summary>
        internal static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предельный срок восстановления.
        /// </summary>
        internal static string DeadlineForRecovery {
            get {
                return ResourceManager.GetString("DeadlineForRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдел.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued from {0}th cassette.
        /// </summary>
        internal static string DispCass {
            get {
                return ResourceManager.GetString("DispCass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдано.
        /// </summary>
        internal static string Dispense {
            get {
                return ResourceManager.GetString("Dispense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диспенсер.
        /// </summary>
        internal static string Dispenser {
            get {
                return ResourceManager.GetString("Dispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим работы для инкассации.
        /// </summary>
        internal static string EncashHours {
            get {
                return ResourceManager.GetString("EncashHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО инкассатора.
        /// </summary>
        internal static string Encashman {
            get {
                return ResourceManager.GetString("Encashman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        internal static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание сообщения.
        /// </summary>
        internal static string EventMessage {
            get {
                return ResourceManager.GetString("EventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        internal static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание неисправности.
        /// </summary>
        internal static string FaultDescription {
            get {
                return ResourceManager.GetString("FaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неисправность чекового принтера.
        /// </summary>
        internal static string FaultReceiptPrinter {
            get {
                return ResourceManager.GetString("FaultReceiptPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансовый институт.
        /// </summary>
        internal static string FinancialInstitute {
            get {
                return ResourceManager.GetString("FinancialInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время окончания.
        /// </summary>
        internal static string FinishDateTime {
            get {
                return ResourceManager.GetString("FinishDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогноз. Снято наличных.
        /// </summary>
        internal static string ForcastWithdraw {
            get {
                return ResourceManager.GetString("ForcastWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от банкомата.
        /// </summary>
        internal static string fromAtm {
            get {
                return ResourceManager.GetString("fromAtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от хоста.
        /// </summary>
        internal static string fromHost {
            get {
                return ResourceManager.GetString("fromHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий прогноз.
        /// </summary>
        internal static string GeneralForecast {
            get {
                return ResourceManager.GetString("GeneralForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием наличности.
        /// </summary>
        internal static string GetCash {
            get {
                return ResourceManager.GetString("GetCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение выписок.
        /// </summary>
        internal static string GetStatements {
            get {
                return ResourceManager.GetString("GetStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее время устранения инцидента.
        /// </summary>
        internal static string HourCount {
            get {
                return ResourceManager.GetString("HourCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние инцидента.
        /// </summary>
        internal static string IncidentCondition {
            get {
                return ResourceManager.GetString("IncidentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер инцидента.
        /// </summary>
        internal static string IncidentNumber {
            get {
                return ResourceManager.GetString("IncidentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по инцидентам.
        /// </summary>
        internal static string IncidentReport {
            get {
                return ResourceManager.GetString("IncidentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инциденты.
        /// </summary>
        internal static string Incidents {
            get {
                return ResourceManager.GetString("Incidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуживает.
        /// </summary>
        internal static string InService {
            get {
                return ResourceManager.GetString("InService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP адрес.
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует наличность.
        /// </summary>
        internal static string LackOfCash {
            get {
                return ResourceManager.GetString("LackOfCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие связи.
        /// </summary>
        internal static string LackOfCommunication {
            get {
                return ResourceManager.GetString("LackOfCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менее.
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведение платежей.
        /// </summary>
        internal static string MakingPayments {
            get {
                return ResourceManager.GetString("MakingPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендуемая сумма загрузки.
        /// </summary>
        internal static string MaxSum {
            get {
                return ResourceManager.GetString("MaxSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История сообщений.
        /// </summary>
        internal static string MessageHistory {
            get {
                return ResourceManager.GetString("MessageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст сообщения.
        /// </summary>
        internal static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный остаток.
        /// </summary>
        internal static string MinAmount {
            get {
                return ResourceManager.GetString("MinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служба мониторинга.
        /// </summary>
        internal static string MonitoringService {
            get {
                return ResourceManager.GetString("MonitoringService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Более.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет связи.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определено.
        /// </summary>
        internal static string NotDetermined {
            get {
                return ResourceManager.GetString("NotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotInitialized.
        /// </summary>
        internal static string NotInitialized {
            get {
                return ResourceManager.GetString("NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обслуживает.
        /// </summary>
        internal static string OutOfService {
            get {
                return ResourceManager.GetString("OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место установки.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблема.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрированно.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрированные банкоматы.
        /// </summary>
        internal static string RegisteredAtms {
            get {
                return ResourceManager.GetString("RegisteredAtms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика. Остатки на конец дня.
        /// </summary>
        internal static string Remain {
            get {
                return ResourceManager.GetString("Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогноз. Остатки на конец дня.
        /// </summary>
        internal static string RemainForcast {
            get {
                return ResourceManager.GetString("RemainForcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет создан:.
        /// </summary>
        internal static string ReportCreated {
            get {
                return ResourceManager.GetString("ReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по сводной таблице инцидентов.
        /// </summary>
        internal static string ReportIncidentTable {
            get {
                return ResourceManager.GetString("ReportIncidentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по сообщениям.
        /// </summary>
        internal static string ReportMessages {
            get {
                return ResourceManager.GetString("ReportMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет службы мониторинга банкоматов.
        /// </summary>
        internal static string ReportMonitoringServiceATMs {
            get {
                return ResourceManager.GetString("ReportMonitoringServiceATMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по доступности.
        /// </summary>
        internal static string ReportOnAvailability {
            get {
                return ResourceManager.GetString("ReportOnAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по остаткам наличности (диспенсер).
        /// </summary>
        internal static string ReportOnCashBalances_Dispenser {
            get {
                return ResourceManager.GetString("ReportOnCashBalances_Dispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по остаткам денежной наличности (BNA).
        /// </summary>
        internal static string ReportOnCashBalancesBNA {
            get {
                return ResourceManager.GetString("ReportOnCashBalancesBNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о ходе устранения инцидентов.
        /// </summary>
        internal static string ReportOnTheEliminationOfIncidents {
            get {
                return ResourceManager.GetString("ReportOnTheEliminationOfIncidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по событиям на банкомате.
        /// </summary>
        internal static string ReportOnTheEventsAtTheAtm {
            get {
                return ResourceManager.GetString("ReportOnTheEventsAtTheAtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о зарегистрированных банкоматах на.
        /// </summary>
        internal static string ReportRegisteredAtmsOf {
            get {
                return ResourceManager.GetString("ReportRegisteredAtmsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводный отчет по инцидентам.
        /// </summary>
        internal static string ReportSummaryIncidents {
            get {
                return ResourceManager.GetString("ReportSummaryIncidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводный отчет по инцидентам. Рабочие инциденты.
        /// </summary>
        internal static string ReportSummaryIncidentsWorkingIncidents {
            get {
                return ResourceManager.GetString("ReportSummaryIncidentsWorkingIncidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по действиям пользователя.
        /// </summary>
        internal static string ReportUserActions {
            get {
                return ResourceManager.GetString("ReportUserActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответсвенность.
        /// </summary>
        internal static string Responsibility {
            get {
                return ResourceManager.GetString("Responsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный.
        /// </summary>
        internal static string ResponsibleFor {
            get {
                return ResourceManager.GetString("ResponsibleFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер маршрута.
        /// </summary>
        internal static string RouteNumber {
            get {
                return ResourceManager.GetString("RouteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUB.
        /// </summary>
        internal static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время отправки заявки.
        /// </summary>
        internal static string SendOrderTime {
            get {
                return ResourceManager.GetString("SendOrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простой из-за отсутствия наличности.
        /// </summary>
        internal static string SimplyBecauseOfTheLackOfCash {
            get {
                return ResourceManager.GetString("SimplyBecauseOfTheLackOfCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серийный номер.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        internal static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функциональный статус.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предположительное время ремонта.
        /// </summary>
        internal static string SupposedRepairTime {
            get {
                return ResourceManager.GetString("SupposedRepairTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Временно не работает.
        /// </summary>
        internal static string TemporarilyNotWorking {
            get {
                return ResourceManager.GetString("TemporarilyNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бумага заканчивается. Журнальный принтер.
        /// </summary>
        internal static string ThePaperEnds_JournalPrinter {
            get {
                return ResourceManager.GetString("ThePaperEnds_JournalPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бумага заканчивается. Чековый принтер.
        /// </summary>
        internal static string ThePaperEnds_ReceiptPrinter {
            get {
                return ResourceManager.GetString("ThePaperEnds_ReceiptPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время создания.
        /// </summary>
        internal static string TimeCreated {
            get {
                return ResourceManager.GetString("TimeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плановая дата выполнения.
        /// </summary>
        internal static string TimeProceedToService {
            get {
                return ResourceManager.GetString("TimeProceedToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая сумма по валютам.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая сумма остатков для группы банкоматов.
        /// </summary>
        internal static string TotalAmountOfBalancesForAGroupOfAtms {
            get {
                return ResourceManager.GetString("TotalAmountOfBalancesForAGroupOfAtms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        internal static string Track2Data {
            get {
                return ResourceManager.GetString("Track2Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип неисправности.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестна.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия пользователя.
        /// </summary>
        internal static string UserActions {
            get {
                return ResourceManager.GetString("UserActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь M3 WEB.
        /// </summary>
        internal static string UserOfM3WEB {
            get {
                return ResourceManager.GetString("UserOfM3WEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номинал.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание ремонта.
        /// </summary>
        internal static string WaitingForRepairs {
            get {
                return ResourceManager.GetString("WaitingForRepairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика. Снято наличных.
        /// </summary>
        internal static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогноз снятия наличных на банкоматах.
        /// </summary>
        internal static string WithdrawCashForecast {
            get {
                return ResourceManager.GetString("WithdrawCashForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим работы для клиентов.
        /// </summary>
        internal static string WorkHours {
            get {
                return ResourceManager.GetString("WorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работает.
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
